# Generated by Django 3.2.5 on 2021-07-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_categ_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categ_id',
            new_name='category',
        ),
    ]
